---

- hosts: all
  become: true
  tasks:
  - name: update resposity index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install osquery package
    apt: 
      name: osquery
      state: latest    
    when: ansible_distribution == "Ubuntu" 

  - name: update resposity index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install osquery package
    dnf: 
      name: osquery
      state: latest    
    when: ansible_distribution == "CentOS" 

